[theme]
theme = "bad-wolf"

[icons]
icons = "awesome4"
# 电池图标自定义

[[block]]
block = "net"
format = " $icon {$ip} via $device "

[[block]]
block = "cpu"
interval = 1
format = "$icon $barchart $utilization "
format_alt = "$icon $frequency{ $boost|} "
[block.theme_overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"
[block.icons_overrides]
cpu_boost_on = "ON"
cpu_boost_off = "OFF"

[[block]]
block = "load"
format = " $icon 1min avg: $1m.eng(w:4) "
interval = 1
[block.theme_overrides]
idle_bg = "#555555"
idle_fg = "#abcdef"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "
[[block.click]]
button = "right"
update = true
[block.theme_overrides]
idle_bg = "#6272a4"
idle_fg = "#f8f8f2"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
#format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
format_alt = " $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi)($mem_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90
[block.theme_overrides]
idle_bg = "#8d8759"
idle_fg = "#ffe5b4"

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
idle_bg = "#7a5c61"
idle_fg = "#ffd700"

[[block]]
block = "xrandr"
format = " $icon    $brightness $resolution "
[block.theme_overrides]
idle_bg = "#3a506b"
idle_fg = "#faf3dd"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon   $timestamp.datetime(f:'%Y-%m-%d %R', l:fr_BE) "
short = " $icon   $timestamp.datetime(f:%R) "
[block.theme_overrides]
idle_bg = "#1b263b"
idle_fg = "#eae2b7"
